<a href="https://colab.research.google.com/github/Cho-mindong/study_ai_pre-cousre/blob/master/Numpy%EC%9D%98_%EA%B8%B0%EB%B3%B8_%EC%82%AC%EC%9A%A9%EB%B2%95%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy의 기본 사용법
[강의 노트](https://github.com/ndb796/Python-Data-Analysis-and-Image-Processing-Tutorial/blob/master/04.%20Numpy%EC%9D%98%20%EC%97%B0%EC%82%B0%EA%B3%BC%20%ED%95%A8%EC%88%98/Python%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B3%BC%20%EC%9D%B4%EB%AF%B8%EC%A7%80%20%EC%B2%98%EB%A6%AC%20-%20Numpy%EC%9D%98%20%EC%97%B0%EC%82%B0%EA%B3%BC%20%ED%95%A8%EC%88%98.pdf)

Python의 Numpy 라이브러리는 List와 **상호 변환이 가능**합니다.

In [0]:
import numpy as np   #numpy를 np로 

array=np.array([1,2,3])  #리스트를 numpy로
print(array.size)        #array의 사이즈 len과 비슷
print(array.dtype)       #array 원소의 타입
print(array[2])         #array도 list처럼 인덱스사용 가능

3
int64
3


Python의 Numpy 라이브러리는 **다양한 형태의 배열**을 초기화 할 수 있습니다.

In [0]:
import numpy as np

# 0부터 3까지의 배열 만들기
array1=np.arange(4)   #range처럼 arange를 통해 사용
print(array1)

# 0으로 초기화
array2=np.zeros((4,4),dtype=float) # (4행,4열)로 배열의 원소를 0으로 통일 ,배열의 원소를 실수로 변환
print(array2)

# 1로 초기화
array3=np.ones((3,3),dtype=str)#(3행,3열)로 배열의 원소를 1로 통일,배열의 원소를 문자열로 변환
print(array3)

# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4=np.random.randint(0,10,(3,3))   #random매서드를 이용해 0~10까지의 숫자중 골라 3행 3열로 만들기
print(array4)

# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5=np.random.normal(0,1,(3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[9 9 3]
 [0 6 8]
 [2 5 8]]
[[ 1.20594912  2.01669888 -1.8510393 ]
 [-0.46414424 -0.8064136  -1.12917878]
 [ 0.86492113 -0.98108579 -0.95893811]]


Numpy는 다양한 형태로 **합치기가 가능** 있습니다.

In [0]:
import numpy as np

array1=np.array([1,2,3])
array2=np.array([4,5,6])
array3=np.concatenate([array1,array2]) #concatenate매서드를 이용해 가로로 합치기
print(array3.shape) # shape매서드는 행렬의 형태를 나타내줌 (행,열)
print(array3)

(6,)
[1 2 3 4 5 6]


Numpy를 위 아래로 합칠 수 있습니다.

In [0]:
import numpy as np
#axis=0 기준
array1=np.arange(4).reshape(1,4) #reshape로 행렬의 모양 만들기
array2=np.arange(8).reshape(2,4)  #reshape로 행렬의 모양 만들기
array3=np.concatenate([array1,array2], axis=0) #concatenate 매서드로 합치기, axis=0을 넣어 위 아래로 합치기
#axis는 함수의 축을 나타내는 것. axis=0 is x축(정육면체가 있을때 밑면의 가로)/ axis=1 is y축(정육면체가 있을때 높이) / axis=2 is z축(정육면체에서 밑면의 세로)
#axis=0 이면 x축을 기준으로 합친다. 이때 행렬의형태에 따라 기준을 정하는데 한계가 있다
print(array3.shape)
print(array3)
print()
#axis=1 기준
array4=np.arange(4).reshape(2,2)
array5=np.arange(8).reshape(2,4)
array6=np.concatenate([array4,array5], axis=1)
#axis=1 y축을 기준으로 합침
print(array6.shape)
print(array6)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]

(2, 6)
[[0 1 0 1 2 3]
 [2 3 4 5 6 7]]


Numpy의 **형태를 변경**할 수 있습니다.

In [0]:
import numpy as np

array1=np.array([1,2,3,4]) #array1의 행렬 형태는 (1,4) 따로 reshape매서드를 이용하지 않으면 shape매서드를 활용해 출력하면 (4,)로 출력된다
array2=array1.reshape((2,2)) #reshape method를 이용해 (2,2)형태로 바꿈
print(array1.shape)
print(array2.shape)

(4,)
(2, 2)


Numpy의 **형태를 나누기** 할 수 있습니다.

In [0]:
import numpy as np

array = np.arange(8).reshape(2, 4)
print(array)
left, right = np.split(array, [2], axis=1) #np.split(배열, 기준이될 인덱스, 기준이 될 축)
#axis=1 즉,y축으로 나누기

print(left.shape)
print(right.shape)
print(right[1][1])

[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)
7
